import * as React from 'react'
import { StyleSheet, View, Text } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import Tabs from '../../components/buttons/Tabs'
import AddressQrCode from '../../components/wallet/AddressQrCode'
import ActiveButton from '../../components/buttons/ActiveButton'
import LinkButton from '../../components/buttons/LinkButton'

const Pair2FaDeviceView = ({ navigation, route }) => {
  return (
    <SafeAreaView style={styles.safeArea}>
      <View style={styles.screen}>
        <Text style={styles.text}>
          Enter the code generated by your authentication device to unpair the devices
        </Text>
        <View style={styles.otpInput}>
          <Tabs
            tabs={[{ name: 'QR Code', selected: true }, { name: 'Text Code' }]}
            style={styles.tabHeader}
          />
          <AddressQrCode address='abc123' />
          <View style={styles.linkButtons}>
            <View style={styles.linkButton}>
              <LinkButton title='Copy QR Code to Clipboard' />
            </View>
            <View style={styles.linkButton}>
              <LinkButton title='Share QR Code' />
            </View>
          </View>
          <ActiveButton
            title='Next'
          />
        </View>
      </View>
    </SafeAreaView>
  )
}

const styles = StyleSheet.create({
  safeArea: {
    width: '100%'
  },
  screen: {
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'flex-start',
    minHeight: '100%'
  },
  text: {
    paddingHorizontal: '20px',
    paddingVertical: '16px'
  },
  otpInput: {
    paddingHorizontal: '20px',
    paddingVertical: '16px'
  },
  linkButtons: {
    paddingTop: '16px',
    paddingBottom: '12px'
  },
  linkButton: {
    paddingBottom: '8px'
  }
})

export default Pair2FaDeviceView
