import * as React from 'react'
import { StyleSheet, View, Text } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import OtpInput from '../../components/inputs/OtpInput'

const Verify2FaDeviceView = ({ navigation, route }) => {
  return (
    <SafeAreaView style={styles.safeArea}>
      <View style={styles.screen}>
        <Text style={styles.text}>
          Enter the code generated by your authentication device to unpair the devices
        </Text>
        <View style={styles.otpInput}>
          <OtpInput />
        </View>
      </View>
    </SafeAreaView>
  )
}

const styles = StyleSheet.create({
  safeArea: {
    width: '100%'
  },
  screen: {
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'flex-start',
    minHeight: '100%'
  },
  text: {
    paddingHorizontal: '20px',
    paddingVertical: '16px'
  },
  otpInput: {
    paddingHorizontal: '20px',
    paddingVertical: '16px'
  }
})

export default Verify2FaDeviceView
